fix: workflow error

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,13 +13,14 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Run Script on Remote Server
+      - name: ssh connect server
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SSH_HOST }} # ip address
           username: ${{ secrets.SSH_USER }} # server username
           key: ${{ secrets.SSH_PRIVATE_KEY }} # server ssh private key
           script: |
+            BLOG_PATH_REMOTE=${{ secrets.BLOG_PATH_REMOTE }}
             cd $BLOG_PATH_REMOTE
 
             MAX_RETRIES=8
@@ -41,3 +42,34 @@ jobs:
               exit 1  # throw error
             fi
             EOF
+
+      - name: Run Script to Push serve
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          SSH_HOST: ${{ secrets.SSH_HOST }}
+          SSH_USER: ${{ secrets.SSH_USER }}
+          BLOG_PATH_REMOTE: ${{ secrets.BLOG_PATH_REMOTE }}
+        run: |
+          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
+          ssh $SSH_USER@$SSH_HOST  << EOF
+          cd $BLOG_PATH_REMOTE
+
+          MAX_RETRIES=8
+          RETRY_COUNT=0
+
+          while [ \$RETRY_COUNT -lt \$MAX_RETRIES ]; do
+            if git pull origin main; then
+              break  # pull succesful exit
+            else
+              echo "Git pull failed, retrying (\$((RETRY_COUNT + 1)) of \$MAX_RETRIES)..."
+              ((RETRY_COUNT++))
+              sleep 5
+            fi
+          done
+
+          # check if retry count exceeded
+          if [ \$RETRY_COUNT -eq \$MAX_RETRIES ]; then
+            echo "Failed to pull code after \$MAX_RETRIES attempts. Exiting."
+            exit 1  # throw error
+          fi
+          EOF
